#!/usr/bin/env Rscript
# harness/research/propose.R
#
# Turns the winning candidate into (a) an edit to the environment pin and
# (b) a PROPOSAL.md a human can actually adjudicate.
#
# The document is the deliverable. A PR that says "bump the snapshot" forces the
# reviewer to reconstruct the evidence themselves, which is precisely the manual
# work this harness exists to eliminate. So PROPOSAL.md must answer, without the
# reviewer opening anything else:
#
#   What changed?  What did it do to the results?  How close to the tolerance
#   did we get?  What is the risk of the new packages?  Why should I believe it?
#
# Usage: Rscript propose.R <recommendation.json> <repo-root>

args <- commandArgs(trailingOnly = TRUE)
rec_file <- if (length(args) >= 1) args[1] else "artifacts/recommendation.json"
root     <- if (length(args) >= 2) args[2] else "."

`%||%` <- function(a, b) if (is.null(a) || length(a) == 0 || is.na(a[1])) b else a
fmt    <- function(x, d = 3) if (is.null(x) || is.na(x)) "n/a" else format(round(as.numeric(x), d), scientific = FALSE)

rec <- jsonlite::fromJSON(rec_file, simplifyVector = FALSE)

if ((rec$recommendation %||% "NONE") != "PROPOSE") {
  message("No proposal this week: ", rec$reason %||% "unspecified")
  writeLines("NONE", file.path(root, ".proposal-status"))
  quit(status = 0)
}

# Domain-specific closing material, if the use case provides any.
usecase_footer <- function(root) {
  ucroot <- tryCatch(
    system2("harness/usecase", "root", stdout = TRUE, stderr = NULL),
    error = function(e) character(0))
  if (!length(ucroot) || !nzchar(ucroot[[1]])) return(character(0))
  f <- file.path(root, ucroot[[1]], "proposal-footer.md")
  if (!file.exists(f)) return(character(0))
  readLines(f, warn = FALSE)
}

cand <- rec$candidate
raw  <- rec$raw %||% list()
id   <- cand$candidate_id %||% "unknown"

# ---- apply the change, via the use case ------------------------------------
#
# The harness knows a dimension should move. It does not know which file holds
# that pin or what its syntax is, and it must not learn: the moment this script
# contains a pin file path from one domain, the harness only works for
# one domain. Ask the use case to do it.
#
# Exit 3 from `apply` means "already current". That is a successful outcome,
# not an error.

dimension <- cand$dimension %||% ""
new_value <- raw$candidate_value %||% cand$value %||% ""

apply_cmd <- system2("harness/usecase", c("cmd", "apply"), stdout = TRUE, stderr = NULL)
status <- 3L
applied <- "none"
if (length(apply_cmd) == 1 && nzchar(apply_cmd) && nzchar(dimension) && nzchar(new_value)) {
  out <- system2(apply_cmd, c(shQuote(dimension), shQuote(new_value)),
                 stdout = TRUE, stderr = "")
  status <- attr(out, "status") %||% 0L
  if (identical(as.integer(status), 0L) && length(out)) applied <- trimws(out[[1]])
} else {
  message("No `apply` capability declared, or no dimension/value to apply.")
}

# ---- refuse to propose a change that is not a change ----------------------
#
# A proposal PR exists to spend a scarce resource: one human review per week.
# Opening one that edits no environment pin trains the reviewer to skim, which
# is precisely the failure mode this harness is built to avoid. If nothing was
# applied, say so and let the workflow record a quiet week instead.

status_path <- file.path(root, ".proposal-status.json")
if (identical(applied, "none")) {
  writeLines(c(
    "{",
    '  "changed": false,',
    sprintf('  "candidate": "%s",', id),
    sprintf('  "dimension": "%s",', dimension),
    '  "reason": "the winning candidate produced no edit to any environment pin"',
    "}"
  ), status_path)
  message("")
  message("NO-OP PROPOSAL: candidate '", id, "' (dimension '", dimension,
          "') matches the incumbent pin.")
  message("Not opening a pull request. This is a successful outcome: the ",
          "research loop confirmed the current pin is still the best available.")
  quit(status = 0)
}
writeLines(c("{", '  "changed": true,',
             sprintf('  "candidate": "%s",', id),
             sprintf('  "applied": "%s"', applied), "}"), status_path)

# ---- compose the proposal -------------------------------------------------

verdict <- cand$verdict %||% "UNKNOWN"
tol     <- as.numeric(cand$tol_util %||% NA)

L <- c(
  sprintf("# Environment proposal: `%s`", id),
  "",
  "> Generated by the nightly research loop and aggregated by",
  "> `harness/research/weekly-proposal.yml`. Every number below was produced by",
  "> an unattended run against the real validation payload -- nothing here is",
  "> asserted by an agent without evidence.",
  "",
  "## 1. What is being proposed",
  "",
  sprintf("| | |"),
  sprintf("|---|---|"),
  sprintf("| Candidate | `%s` |", id),
  sprintf("| Track | %s |", cand$track %||% "n/a"),
  sprintf("| Dimension changed | `%s` |", dimension),
  sprintf("| Change applied | %s |", applied),
  sprintf("| Delta verdict | **%s** |", verdict),
  "",
  "## 2. Effect on results (the question that matters)",
  ""
)

L <- c(L, switch(verdict,
  "IDENTICAL" = c(
    "The inputs changed and **the results did not**. Output checksums are",
    "bit-for-bit identical to the incumbent. This is the strongest possible",
    "outcome: the change is invisible to the science."),
  "PASS_WITH_CHANGES" = c(
    "Package versions moved and every validation assertion still passed under the",
    "strict criterion. Output checksums are unchanged."),
  "TOLERANT_DRIFT" = c(
    "Numeric outputs moved but stayed inside the declared business tolerance.",
    "**Review the tolerance utilisation below before accepting** -- a change that",
    "passes at 95% of tolerance has consumed nearly all the available headroom."),
  "BASELINE_ESTABLISHED" = c(
    "No incumbent manifest was available to diff against, so this run recorded a",
    "baseline rather than a comparison. **The PQ result below is still meaningful**",
    "-- the payload was validated against the committed fixtures -- but the",
    "package-level delta is not, because there was nothing to compare with.",
    "Expect a real delta on the next cycle."),
  "NOT_EVALUATED" = c(
    "This candidate was never evaluated; treat every metric below as absent",
    "rather than as a pass."),
  c(sprintf("Verdict `%s` is not recognised by `propose.R`. Inspect `delta.md` in the",
            verdict),
    "run artifacts before acting, and add this verdict to the interpretation map",
    "-- an unexplained verdict in a regulatory proposal is a defect in the harness.")
))

L <- c(L, "",
  "| Metric | Value | Reading |",
  "|---|---|---|",
  sprintf("| PQ assertions passed | %s | |", fmt(cand$pq_passed, 0)),
  sprintf("| PQ assertions failed | %s | must be 0 to be proposable |", fmt(cand$pq_failed, 0)),
  sprintf("| Tolerance utilisation | %s | %s |", fmt(tol),
          if (is.na(tol)) "no numeric comparison recorded"
          else if (tol > 0.8) "**HIGH - little headroom remains**"
          else if (tol > 0.5) "moderate"
          else "comfortable"),
  sprintf("| Package churn | %s | number of packages added/removed/changed |", fmt(cand$pkg_churn, 0)),
  sprintf("| Build time | %s s | |", fmt(cand$build_seconds, 0)),
  sprintf("| Image size | %s MB | |", fmt(cand$image_size_mb, 0)),
  "",
  "`tolerance utilisation` is the worst observed deviation divided by its declared",
  "tolerance. Pass/fail counts hide this: a run passing at 0.99 is one upstream",
  "change away from failing, and that is worth knowing before you merge.",
  "")

if (!is.null(rec$runner_up)) {
  ru <- rec$runner_up
  L <- c(L,
    "## 3. What it was chosen over", "",
    "| | Recommended | Runner-up |", "|---|---|---|",
    sprintf("| Candidate | `%s` | `%s` |", id, ru$candidate_id %||% "n/a"),
    sprintf("| Verdict | %s | %s |", verdict, ru$verdict %||% "n/a"),
    sprintf("| Churn | %s | %s |", fmt(cand$pkg_churn, 0), fmt(ru$pkg_churn, 0)),
    sprintf("| Build time | %s s | %s s |", fmt(cand$build_seconds, 0), fmt(ru$build_seconds, 0)),
    "",
    "Ranking policy (in order): result stability, tolerance headroom, low churn,",
    "build time. Build time is last deliberately -- speed never outranks a change",
    "in the numbers.", "")
} else {
  L <- c(L, "## 3. What it was chosen over", "",
    sprintf("%s candidate(s) were evaluated this week; %s cleared the gates.",
            rec$evaluated %||% "?", rec$eligible %||% "?"),
    "See `weekly-summary.csv` attached to this PR for the full table including",
    "candidates that were rejected and why.", "")
}

L <- c(L,
  "## 4. Rejected candidates", "",
  "| Candidate | Status | Verdict | Blocked by |",
  "|---|---|---|---|")

detail <- rec$detail
if (!is.null(detail)) {
  for (r in detail) {
    if (isTRUE(r$eligible)) next
    L <- c(L, sprintf("| `%s` | %s | %s | %s |",
                      r$candidate_id %||% "?", r$status %||% "?",
                      r$verdict %||% "-", r$blocked_by %||% "-"))
  }
}

L <- c(L, "",
  "A rejected candidate is a successful experiment. It cost no review time and it",
  "told us something about the upgrade path.", "",
  "## 5. Evidence and references", "",
  sprintf("- Nightly run: `%s`", raw$run_id %||% "see telemetry"),
  sprintf("- Recorded: `%s`", raw$timestamp %||% "n/a"),
  "- Full telemetry: `research/telemetry` branch, `evidence/metrics/metrics.jsonl`",
  "- Delta report: `evidence/delta/` in the run artifacts",
  "- Qualification detail: JUnit XML in `evidence/qualify/`",
  "",
  # The use case supplies its own methodology citations. The harness has no
  # opinion about which papers justify a domain it has never heard of.
  usecase_footer(root),
  "",
  "## 7. What this PR does NOT claim", "",
  "This is evidence, not a decision. The harness cannot know whether the changed",
  "packages touch a domain where your therapeutic area has additional",
  "expectations, and it cannot sign anything. Approving this PR is a human",
  "judgement that the recorded deltas are acceptable for your programme.",
  "",
  "---",
  sprintf("_Proposal generated %s_", format(Sys.time(), "%Y-%m-%d %H:%M:%S UTC", tz = "UTC"))
)

dir.create(file.path(root, "evidence/proposals"), recursive = TRUE, showWarnings = FALSE)
out <- file.path(root, "evidence/proposals", sprintf("%s-%s.md", format(Sys.Date(), "%Y-%m-%d"), id))
writeLines(L, out)
writeLines(L, file.path(root, "PROPOSAL.md"))
writeLines("PROPOSE", file.path(root, ".proposal-status"))
writeLines(id, file.path(root, ".proposal-id"))

message("Wrote proposal: ", out)
