#!/usr/bin/env Rscript
# harness/research/propose.R
#
# Turns the winning candidate into (a) an edit to the environment pin and
# (b) a PROPOSAL.md a human can actually adjudicate.
#
# The document is the deliverable. A PR that says "bump the snapshot" forces the
# reviewer to reconstruct the evidence themselves, which is precisely the manual
# work this harness exists to eliminate. So PROPOSAL.md must answer, without the
# reviewer opening anything else:
#
#   What changed?  What did it do to the results?  How close to the tolerance
#   did we get?  What is the risk of the new packages?  Why should I believe it?
#
# Usage: Rscript propose.R <recommendation.json> <repo-root>

args <- commandArgs(trailingOnly = TRUE)
rec_file <- if (length(args) >= 1) args[1] else "artifacts/recommendation.json"
root     <- if (length(args) >= 2) args[2] else "."

`%||%` <- function(a, b) if (is.null(a) || length(a) == 0 || is.na(a[1])) b else a
fmt    <- function(x, d = 3) if (is.null(x) || is.na(x)) "n/a" else format(round(as.numeric(x), d), scientific = FALSE)

rec <- jsonlite::fromJSON(rec_file, simplifyVector = FALSE)

if ((rec$recommendation %||% "NONE") != "PROPOSE") {
  message("No proposal this week: ", rec$reason %||% "unspecified")
  writeLines("NONE", file.path(root, ".proposal-status"))
  quit(status = 0)
}

cand <- rec$candidate
raw  <- rec$raw %||% list()
id   <- cand$candidate_id %||% "unknown"

# ---- apply the pin change -------------------------------------------------

dimension <- cand$dimension %||% ""
new_value <- raw$candidate_value %||% cand$value %||% ""

applied <- "none"
if (dimension == "ppm_snapshot" && nzchar(new_value)) {
  f <- file.path(root, "env/renv/ppm-snapshot.txt")
  txt <- readLines(f, warn = FALSE)
  old <- sub("^PPM_SNAPSHOT=", "", grep("^PPM_SNAPSHOT=", txt, value = TRUE)[1])
  txt <- sub("^PPM_SNAPSHOT=.*", paste0("PPM_SNAPSHOT=", new_value), txt)
  writeLines(txt, f)
  applied <- sprintf("PPM snapshot %s -> %s", old, new_value)
  message("Applied: ", applied)
} else if (dimension == "nixpkgs_date" && nzchar(new_value)) {
  f <- file.path(root, "env/nix/nixpkgs-pin.txt")
  if (file.exists(f)) {
    txt <- readLines(f, warn = FALSE)
    old <- sub("^NIXPKGS_DATE=", "", grep("^NIXPKGS_DATE=", txt, value = TRUE)[1])
    txt <- sub("^NIXPKGS_DATE=.*", paste0("NIXPKGS_DATE=", new_value), txt)
    writeLines(txt, f)
    applied <- sprintf("nixpkgs date %s -> %s", old, new_value)
  }
} else if (dimension == "base_digest") {
  applied <- "base image digest refresh (see delta below)"
}

# ---- compose the proposal -------------------------------------------------

verdict <- cand$verdict %||% "UNKNOWN"
tol     <- as.numeric(cand$tol_util %||% NA)

L <- c(
  sprintf("# Environment proposal: `%s`", id),
  "",
  "> Generated by the nightly research loop and aggregated by",
  "> `harness/research/weekly-proposal.yml`. Every number below was produced by",
  "> an unattended run against the real validation payload -- nothing here is",
  "> asserted by an agent without evidence.",
  "",
  "## 1. What is being proposed",
  "",
  sprintf("| | |"),
  sprintf("|---|---|"),
  sprintf("| Candidate | `%s` |", id),
  sprintf("| Track | %s |", cand$track %||% "n/a"),
  sprintf("| Dimension changed | `%s` |", dimension),
  sprintf("| Change applied | %s |", applied),
  sprintf("| Delta verdict | **%s** |", verdict),
  "",
  "## 2. Effect on results (the question that matters)",
  ""
)

L <- c(L, switch(verdict,
  "IDENTICAL" = c(
    "The environment changed and **the analysis outputs did not**. ADSL and ADAE",
    "checksums are bit-for-bit identical to the incumbent. This is the strongest",
    "possible outcome: the upgrade is invisible to the science."),
  "PASS_WITH_CHANGES" = c(
    "Package versions moved and every validation assertion still passed under the",
    "strict criterion. Output checksums are unchanged."),
  "TOLERANT_DRIFT" = c(
    "Numeric outputs moved but stayed inside the declared business tolerance.",
    "**Review the tolerance utilisation below before accepting** -- a change that",
    "passes at 95% of tolerance has consumed nearly all the available headroom."),
  c("Verdict not recognised; inspect `delta.md` in the run artifacts before acting.")
))

L <- c(L, "",
  "| Metric | Value | Reading |",
  "|---|---|---|",
  sprintf("| PQ assertions passed | %s | |", fmt(cand$pq_passed, 0)),
  sprintf("| PQ assertions failed | %s | must be 0 to be proposable |", fmt(cand$pq_failed, 0)),
  sprintf("| Tolerance utilisation | %s | %s |", fmt(tol),
          if (is.na(tol)) "no numeric comparison recorded"
          else if (tol > 0.8) "**HIGH - little headroom remains**"
          else if (tol > 0.5) "moderate"
          else "comfortable"),
  sprintf("| Package churn | %s | number of packages added/removed/changed |", fmt(cand$pkg_churn, 0)),
  sprintf("| Build time | %s s | |", fmt(cand$build_seconds, 0)),
  sprintf("| Image size | %s MB | |", fmt(cand$image_size_mb, 0)),
  "",
  "`tolerance utilisation` is the worst observed deviation divided by its declared",
  "tolerance. Pass/fail counts hide this: a run passing at 0.99 is one upstream",
  "change away from failing, and that is worth knowing before you merge.",
  "")

if (!is.null(rec$runner_up)) {
  ru <- rec$runner_up
  L <- c(L,
    "## 3. What it was chosen over", "",
    "| | Recommended | Runner-up |", "|---|---|---|",
    sprintf("| Candidate | `%s` | `%s` |", id, ru$candidate_id %||% "n/a"),
    sprintf("| Verdict | %s | %s |", verdict, ru$verdict %||% "n/a"),
    sprintf("| Churn | %s | %s |", fmt(cand$pkg_churn, 0), fmt(ru$pkg_churn, 0)),
    sprintf("| Build time | %s s | %s s |", fmt(cand$build_seconds, 0), fmt(ru$build_seconds, 0)),
    "",
    "Ranking policy (in order): result stability, tolerance headroom, low churn,",
    "build time. Build time is last deliberately -- speed never outranks a change",
    "in the numbers.", "")
} else {
  L <- c(L, "## 3. What it was chosen over", "",
    sprintf("%s candidate(s) were evaluated this week; %s cleared the gates.",
            rec$evaluated %||% "?", rec$eligible %||% "?"),
    "See `weekly-summary.csv` attached to this PR for the full table including",
    "candidates that were rejected and why.", "")
}

L <- c(L,
  "## 4. Rejected candidates", "",
  "| Candidate | Status | Verdict | Blocked by |",
  "|---|---|---|---|")

detail <- rec$detail
if (!is.null(detail)) {
  for (r in detail) {
    if (isTRUE(r$eligible)) next
    L <- c(L, sprintf("| `%s` | %s | %s | %s |",
                      r$candidate_id %||% "?", r$status %||% "?",
                      r$verdict %||% "-", r$blocked_by %||% "-"))
  }
}

L <- c(L, "",
  "A rejected candidate is a successful experiment. It cost no review time and it",
  "told us something about the upgrade path.", "",
  "## 5. Package risk", "",
  "`riskmetric` scores for any newly introduced package are in `risk-scan.json`",
  sprintf("in the run artifacts. The gate requires a minimum score of %s.",
          rec$risk_min %||% "0.5"),
  "",
  "## 6. Evidence and references", "",
  sprintf("- Nightly run: `%s`", raw$run_id %||% "see telemetry"),
  sprintf("- Recorded: `%s`", raw$timestamp %||% "n/a"),
  "- Full telemetry: `research/telemetry` branch, `evidence/metrics/metrics.jsonl`",
  "- Four-layer delta: `delta.md` / `delta.json` in the run artifacts",
  "- PQ detail: `test-results.xml` (JUnit), `pq-summary.json`",
  "",
  "Methodology basis:",
  "",
  "- Three-phase decoupled validation and the strict/tolerant criterion:",
  "  `pfizer-rd/rvalidation-refactored`",
  "- Dated snapshot pinning for repeatable deployments: Posit,",
  "  *Containerization in Posit Connect*",
  "- Submissions cite exact R and package versions:",
  "  `philbowsher/Open-Source-in-New-Drug-Applications-NDAs-FDA`",
  "- Package risk scoring: R Validation Hub `{riskmetric}`",
  "- Nix-based full-closure pinning (Track B): `ropensci/rix`",
  "",
  "## 7. What this PR does NOT claim", "",
  "This is evidence, not a decision. The harness cannot know whether the changed",
  "packages touch a domain where your therapeutic area has additional",
  "expectations, and it cannot sign anything. Approving this PR is a human",
  "judgement that the recorded deltas are acceptable for your programme.",
  "",
  "---",
  sprintf("_Proposal generated %s_", format(Sys.time(), "%Y-%m-%d %H:%M:%S UTC", tz = "UTC"))
)

dir.create(file.path(root, "evidence/proposals"), recursive = TRUE, showWarnings = FALSE)
out <- file.path(root, "evidence/proposals", sprintf("%s-%s.md", format(Sys.Date(), "%Y-%m-%d"), id))
writeLines(L, out)
writeLines(L, file.path(root, "PROPOSAL.md"))
writeLines("PROPOSE", file.path(root, ".proposal-status"))
writeLines(id, file.path(root, ".proposal-id"))

message("Wrote proposal: ", out)
