# GENERATED by rix::rix_init() via env/nix/generate_env.R — do not edit by hand.
#
# Prevents the Nix-provided R from picking up packages out of the user's system
# library. Without this, a locally installed package can silently shadow the
# pinned one and the environment stops being reproducible.

if (Sys.getenv("NIX_STORE") != "") {
  .libPaths(grep("nix/store", .libPaths(), value = TRUE))
}
options(
  repos = c(CRAN = "https://cloud.r-project.org"),
  install.packages.check.source = "no"
)
